name: Saludo usando variables
run-name: ¡Estoy aprendiendo a usar Variables!
on: workflow_dispatch
env:
  DIA_DE_SEMANA: Lunes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludar
        run: echo "$SALUDO, $NOMBRE. Hoy es $DIA_DE_SEMANA!"
        env:
          NOMBRE: Juan
  saludo-secreto:
    runs-on: ubuntu-latest
      env:
        SALUDO: Hola
    steps:
      - name: Saludar con secreto
        run: echo "$SALUDO, ${{vars.NOMBRE}}. Tu contraseña es ${{secrets.CONTRASENA}}"
